export function apiDocsHtml(): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Calorie Tracker API Swagger</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.18.2/swagger-ui.css">
  <style>
    body { margin: 0; background: #f7f8fb; }
    .topbar { display: none; }
    .swagger-ui .info { margin: 28px 0; }
    .swagger-ui .scheme-container {
      box-shadow: none;
      border: 1px solid #dfe3ea;
      border-radius: 8px;
    }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5.18.2/swagger-ui-bundle.js"></script>
  <script>
    window.ui = SwaggerUIBundle({
      url: "/openapi.json",
      dom_id: "#swagger-ui",
      deepLinking: true,
      displayRequestDuration: true,
      persistAuthorization: true,
      tryItOutEnabled: true,
      presets: [SwaggerUIBundle.presets.apis],
      layout: "BaseLayout"
    });
  </script>
</body>
</html>`;
}

export function openApiSpec(origin: string): Record<string, unknown> {
  return {
    openapi: "3.1.0",
    info: {
      title: "Calorie Tracker API",
      version: "0.1.0",
      description:
        "Cloudflare Workers backend for food text parsing, D1-based nutrition previews, meal logs, daily summaries, and user profiles. Use the Authorize button with a Supabase access token for protected endpoints.",
    },
    servers: [{ url: origin }],
    tags: [
      { name: "Health" },
      { name: "Food" },
      { name: "Meals" },
      { name: "Summary" },
      { name: "History" },
      { name: "Profile" },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description: "Paste a Supabase access token. Swagger will send it as Authorization: Bearer <token>.",
        },
      },
      schemas: schemas(),
    },
    paths: {
      "/": {
        get: {
          tags: ["Health"],
          summary: "Health check",
          security: [],
          responses: {
            "200": jsonResponse("Health response", "HealthResponse"),
          },
        },
      },
      "/api/food/parse": {
        post: {
          tags: ["Food"],
          summary: "Parse natural food text",
          description: "Uses Workers AI only for parsing and normalization. Nutrition values are not generated by AI.",
          security: [{ bearerAuth: [] }],
          requestBody: jsonBody("Parse request", "ParseFoodRequest"),
          responses: {
            "200": jsonResponse("Parsed food items", "ParseFoodResponse"),
            "400": errorResponse(),
            "401": errorResponse(),
          },
        },
      },
      "/api/food/preview": {
        post: {
          tags: ["Food"],
          summary: "Preview nutrition",
          description: "Matches parsed foods against D1 and calculates nutrition from stored per-100g values.",
          security: [{ bearerAuth: [] }],
          requestBody: jsonBody("Preview request", "PreviewFoodRequest"),
          responses: {
            "200": jsonResponse("Nutrition preview", "NutritionPreviewResponse"),
            "400": errorResponse(),
            "401": errorResponse(),
          },
        },
      },
      "/api/food/search": foodSearchPath(),
      "/api/foods/search": foodSearchPath("Alias food search route"),
      "/api/meals": {
        post: {
          tags: ["Meals"],
          summary: "Save a confirmed meal",
          security: [{ bearerAuth: [] }],
          requestBody: jsonBody("Save meal request", "SaveMealRequest"),
          responses: {
            "201": jsonResponse("Saved meal response", "SaveMealResponse"),
            "400": errorResponse(),
            "401": errorResponse(),
          },
        },
        get: {
          tags: ["Meals"],
          summary: "Get meals by date",
          security: [{ bearerAuth: [] }],
          parameters: [dateQuery()],
          responses: {
            "200": jsonResponse("Meals response", "MealsResponse"),
            "400": errorResponse(),
            "401": errorResponse(),
          },
        },
      },
      "/api/meals/{id}": {
        delete: {
          tags: ["Meals"],
          summary: "Delete a meal",
          security: [{ bearerAuth: [] }],
          parameters: [
            {
              name: "id",
              in: "path",
              required: true,
              schema: { type: "string" },
              example: "meal_550e8400-e29b-41d4-a716-446655440000",
            },
            dateQuery(),
          ],
          responses: {
            "200": jsonResponse("Deleted meal response", "DeleteMealResponse"),
            "400": errorResponse(),
            "401": errorResponse(),
            "404": errorResponse(),
          },
        },
      },
      "/api/daily-summary": {
        get: {
          tags: ["Summary"],
          summary: "Get daily nutrition summary",
          security: [{ bearerAuth: [] }],
          parameters: [dateQuery()],
          responses: {
            "200": jsonResponse("Daily summary response", "DailySummaryResponse"),
            "400": errorResponse(),
            "401": errorResponse(),
          },
        },
      },
      "/api/history": {
        get: {
          tags: ["History"],
          summary: "Get recent nutrition history",
          security: [{ bearerAuth: [] }],
          parameters: [
            {
              name: "from",
              in: "query",
              required: true,
              schema: { type: "string", format: "date" },
              example: "2026-06-11",
            },
            {
              name: "to",
              in: "query",
              required: true,
              schema: { type: "string", format: "date" },
              example: "2026-06-17",
            },
          ],
          responses: {
            "200": jsonResponse("History response", "HistoryResponse"),
            "400": errorResponse(),
            "401": errorResponse(),
          },
        },
      },
      "/api/profile": {
        get: {
          tags: ["Profile"],
          summary: "Get profile",
          security: [{ bearerAuth: [] }],
          responses: {
            "200": jsonResponse("User profile", "UserProfile"),
            "401": errorResponse(),
            "404": errorResponse(),
          },
        },
        put: {
          tags: ["Profile"],
          summary: "Upsert profile",
          security: [{ bearerAuth: [] }],
          requestBody: jsonBody("Profile request", "ProfileRequest"),
          responses: {
            "200": jsonResponse("User profile", "UserProfile"),
            "400": errorResponse(),
            "401": errorResponse(),
          },
        },
      },
    },
  };
}

function foodSearchPath(summary = "List or search foods"): Record<string, unknown> {
  return {
    get: {
      tags: ["Food"],
      summary,
      security: [{ bearerAuth: [] }],
      parameters: [
        {
          name: "q",
          in: "query",
          required: false,
          schema: { type: "string", minLength: 1 },
          description: "When omitted, returns the default food list.",
          example: "chowmein",
        },
      ],
      responses: {
        "200": jsonResponse("Food search response", "FoodSearchResponse"),
        "400": errorResponse(),
        "401": errorResponse(),
      },
    },
  };
}

function schemas(): Record<string, unknown> {
  const nutritionValues = {
    type: "object",
    properties: nutritionProperties(),
    required: ["calories", "proteinG", "carbsG", "fatG", "fiberG", "sugarG", "sodiumMg", "calciumMg", "ironMg", "potassiumMg"],
  };

  return {
    HealthResponse: {
      type: "object",
      properties: {
        ok: { type: "boolean", example: true },
        name: { type: "string", example: "calorie-tracker-api" },
      },
      required: ["ok", "name"],
    },
    ErrorResponse: {
      type: "object",
      properties: {
        error: {
          type: "object",
          properties: {
            code: { type: "string", example: "BAD_REQUEST" },
            message: { type: "string", example: "Text is required" },
          },
          required: ["code", "message"],
        },
      },
      required: ["error"],
    },
    ParseFoodRequest: {
      type: "object",
      properties: {
        text: { type: "string", example: "chowmin 1 plate" },
        locale: { type: "string", example: "ne-NP" },
      },
      required: ["text"],
    },
    ParsedFoodItem: {
      type: "object",
      properties: {
        rawText: { type: "string", example: "chowmin 1 plate" },
        canonicalName: { type: "string", example: "vegetable chowmein" },
        quantity: { type: "number", example: 1 },
        unit: { type: "string", example: "plate" },
        estimatedGrams: { type: ["number", "null"], example: 350 },
        estimatedMl: { type: ["number", "null"], example: null },
        confidence: { type: "number", minimum: 0, maximum: 1, example: 0.72 },
        possibleVariants: {
          type: "array",
          items: { type: "string" },
          example: ["vegetable chowmein", "chicken chowmein", "egg chowmein"],
        },
      },
      required: ["rawText", "canonicalName", "quantity", "unit", "estimatedGrams", "estimatedMl", "confidence", "possibleVariants"],
    },
    ParseFoodResponse: {
      type: "object",
      properties: {
        items: { type: "array", items: { $ref: "#/components/schemas/ParsedFoodItem" } },
      },
      required: ["items"],
    },
    PreviewFoodRequest: {
      type: "object",
      properties: {
        items: {
          type: "array",
          items: {
            type: "object",
            properties: {
              canonicalName: { type: "string", example: "vegetable chowmein" },
              quantity: { type: "number", example: 1 },
              unit: { type: "string", example: "plate" },
              grams: { type: "number", example: 350 },
            },
            required: ["canonicalName"],
          },
        },
      },
      required: ["items"],
    },
    NutritionValues: nutritionValues,
    NutritionPreviewItem: {
      allOf: [
        { $ref: "#/components/schemas/NutritionValues" },
        {
          type: "object",
          properties: {
            foodId: { type: ["string", "null"], example: "food_veg_chowmein" },
            name: { type: ["string", "null"], example: "Vegetable Chowmein" },
            inputName: { type: "string", example: "vegetable chowmein" },
            grams: { type: ["number", "null"], example: 350 },
            confidence: { type: "number", example: 0.7 },
            isEstimate: { type: "boolean", example: true },
            needsManualSelection: { type: "boolean", example: false },
          },
          required: ["foodId", "name", "inputName", "grams", "confidence", "isEstimate", "needsManualSelection"],
        },
      ],
    },
    NutritionPreviewResponse: {
      type: "object",
      properties: {
        items: { type: "array", items: { $ref: "#/components/schemas/NutritionPreviewItem" } },
        total: { $ref: "#/components/schemas/NutritionValues" },
      },
      required: ["items", "total"],
    },
    PublicFood: {
      type: "object",
      properties: {
        id: { type: "string", example: "food_veg_chowmein" },
        name: { type: "string", example: "Vegetable Chowmein" },
        aliases: { type: "array", items: { type: "string" }, example: ["chowmin", "veg chowmein", "noodles"] },
        defaultServingName: { type: ["string", "null"], example: "medium plate" },
        defaultServingGrams: { type: ["number", "null"], example: 350 },
        caloriesPer100g: { type: "number", example: 150 },
        proteinPer100g: { type: "number", example: 4 },
        carbsPer100g: { type: "number", example: 21 },
        fatPer100g: { type: "number", example: 5 },
      },
      required: ["id", "name", "aliases", "defaultServingName", "defaultServingGrams", "caloriesPer100g", "proteinPer100g", "carbsPer100g", "fatPer100g"],
    },
    FoodSearchResponse: {
      type: "object",
      properties: {
        items: { type: "array", items: { $ref: "#/components/schemas/PublicFood" } },
      },
      required: ["items"],
    },
    SaveMealItem: {
      allOf: [
        { $ref: "#/components/schemas/NutritionValues" },
        {
          type: "object",
          properties: {
            foodId: { type: ["string", "null"], example: "food_veg_chowmein" },
            foodName: { type: "string", example: "Vegetable Chowmein" },
            quantity: { type: "number", example: 1 },
            unit: { type: "string", example: "plate" },
            grams: { type: "number", example: 350 },
            isEstimate: { type: "boolean", example: true },
            confidence: { type: "number", example: 0.8 },
          },
          required: ["foodName", "grams"],
        },
      ],
    },
    SaveMealRequest: {
      type: "object",
      properties: {
        date: { type: "string", format: "date", example: "2026-06-17" },
        mealType: { type: "string", enum: ["breakfast", "lunch", "dinner", "snack", "other"], example: "lunch" },
        notes: { type: "string", example: "Office lunch" },
        items: { type: "array", items: { $ref: "#/components/schemas/SaveMealItem" } },
      },
      required: ["date", "mealType", "items"],
    },
    DailySummary: {
      allOf: [
        { $ref: "#/components/schemas/NutritionValues" },
        {
          type: "object",
          properties: {
            date: { type: "string", format: "date", example: "2026-06-17" },
          },
          required: ["date"],
        },
      ],
    },
    SaveMealResponse: {
      type: "object",
      properties: {
        mealId: { type: "string", example: "meal_550e8400-e29b-41d4-a716-446655440000" },
        saved: { type: "boolean", example: true },
        dailySummary: { $ref: "#/components/schemas/DailySummary" },
      },
      required: ["mealId", "saved", "dailySummary"],
    },
    MealLog: {
      type: "object",
      properties: {
        id: { type: "string", example: "meal_550e8400-e29b-41d4-a716-446655440000" },
        date: { type: "string", format: "date", example: "2026-06-17" },
        mealType: { type: "string", example: "lunch" },
        notes: { type: ["string", "null"], example: null },
        items: { type: "array", items: { $ref: "#/components/schemas/SaveMealItem" } },
      },
      required: ["id", "date", "mealType", "items"],
    },
    MealsResponse: {
      type: "object",
      properties: {
        items: { type: "array", items: { $ref: "#/components/schemas/MealLog" } },
      },
      required: ["items"],
    },
    DeleteMealResponse: {
      type: "object",
      properties: {
        deleted: { type: "boolean", example: true },
        dailySummary: { $ref: "#/components/schemas/DailySummary" },
      },
      required: ["deleted", "dailySummary"],
    },
    DailySummaryResponse: {
      type: "object",
      properties: {
        date: { type: "string", format: "date", example: "2026-06-17" },
        goal: {
          type: ["object", "null"],
          properties: macroGoalProperties(),
          example: { calories: 2200, proteinG: 120, carbsG: 250, fatG: 70 },
        },
        consumed: { $ref: "#/components/schemas/DailySummary" },
        remaining: {
          type: ["object", "null"],
          properties: macroGoalProperties(),
          example: { calories: 750, proteinG: 58, carbsG: 70, fatG: 22 },
        },
      },
      required: ["date", "goal", "consumed", "remaining"],
    },
    HistoryDay: {
      type: "object",
      properties: {
        date: { type: "string", format: "date", example: "2026-06-17" },
        calories: { type: "number", example: 1450 },
        proteinG: { type: "number", example: 62 },
        mealCount: { type: "number", example: 3 },
      },
      required: ["date", "calories", "proteinG", "mealCount"],
    },
    HistoryResponse: {
      type: "object",
      properties: {
        from: { type: "string", format: "date", example: "2026-06-11" },
        to: { type: "string", format: "date", example: "2026-06-17" },
        items: { type: "array", items: { $ref: "#/components/schemas/HistoryDay" } },
      },
      required: ["from", "to", "items"],
    },
    UserProfile: {
      type: "object",
      properties: {
        id: { type: "string", example: "user_2abc" },
        authProvider: { type: "string", example: "supabase" },
        authUid: { type: "string", example: "user_2abc" },
        name: { type: ["string", "null"], example: "Demo User" },
        email: { type: ["string", "null"], example: "demo@example.com" },
        age: { type: ["number", "null"], example: 25 },
        sex: { type: ["string", "null"], example: "male" },
        heightCm: { type: ["number", "null"], example: 170 },
        weightKg: { type: ["number", "null"], example: 70 },
        activityLevel: { type: ["string", "null"], example: "moderate" },
        goal: { type: ["string", "null"], example: "maintain" },
        dailyCalorieGoal: { type: ["number", "null"], example: 2200 },
        proteinGoalG: { type: ["number", "null"], example: 120 },
        carbsGoalG: { type: ["number", "null"], example: 250 },
        fatGoalG: { type: ["number", "null"], example: 70 },
        createdAt: { type: "string", format: "date-time" },
        updatedAt: { type: "string", format: "date-time" },
      },
      required: ["id", "authProvider", "authUid", "name", "email", "createdAt", "updatedAt"],
    },
    ProfileRequest: {
      type: "object",
      properties: {
        name: { type: "string", example: "Demo User" },
        email: { type: "string", example: "demo@example.com" },
        age: { type: "number", example: 25 },
        sex: { type: "string", example: "male" },
        heightCm: { type: "number", example: 170 },
        weightKg: { type: "number", example: 70 },
        activityLevel: { type: "string", example: "moderate" },
        goal: { type: "string", example: "maintain" },
        dailyCalorieGoal: { type: "number", example: 2200 },
        proteinGoalG: { type: "number", example: 120 },
        carbsGoalG: { type: "number", example: 250 },
        fatGoalG: { type: "number", example: 70 },
      },
    },
  };
}

function nutritionProperties(): Record<string, unknown> {
  return {
    calories: { type: "number", example: 525 },
    proteinG: { type: "number", example: 14 },
    carbsG: { type: "number", example: 72 },
    fatG: { type: "number", example: 18 },
    fiberG: { type: "number", example: 5 },
    sugarG: { type: "number", example: 6 },
    sodiumMg: { type: "number", example: 850 },
    calciumMg: { type: "number", example: 80 },
    ironMg: { type: "number", example: 2.1 },
    potassiumMg: { type: "number", example: 420 },
    vitaminAMcg: { type: "number", example: 0 },
    vitaminCMg: { type: "number", example: 0 },
    vitaminB12Mcg: { type: "number", example: 0 },
  };
}

function macroGoalProperties(): Record<string, unknown> {
  return {
    calories: { type: "number" },
    proteinG: { type: "number" },
    carbsG: { type: "number" },
    fatG: { type: "number" },
  };
}

function dateQuery(): Record<string, unknown> {
  return {
    name: "date",
    in: "query",
    required: true,
    schema: { type: "string", format: "date" },
    example: "2026-06-17",
  };
}

function jsonBody(description: string, schemaName: string): Record<string, unknown> {
  return {
    required: true,
    description,
    content: {
      "application/json": {
        schema: { $ref: `#/components/schemas/${schemaName}` },
      },
    },
  };
}

function jsonResponse(description: string, schemaName: string): Record<string, unknown> {
  return {
    description,
    content: {
      "application/json": {
        schema: { $ref: `#/components/schemas/${schemaName}` },
      },
    },
  };
}

function errorResponse(): Record<string, unknown> {
  return jsonResponse("Error response", "ErrorResponse");
}
